name: 'Backup repository'
description: >
    Create a repository backup

inputs:
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. Default: empty. This field is optional, required if app credentials are not defined.
    default: ${{ github.token }}
  source-repository:
    description: >
        Source repository.
    required: true
  target-repository:
    description: >
        Target repository name.
    required: true
  ref:
    description: >
        Repository hash to copy.
    required: true
  topics:
    description: >
        Topics to add on destination repository
    default: ''

runs:
  using: "composite"
  steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        repository: ${{ inputs.source-repository }}
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token }}
        path: tmp-repo
    - run: |
        IFS='/'
        read -a repo <<< "${{ inputs.target-repository }}"
        HTTPD_CODE=$(curl -X POST -o /dev/null -s -w "%{http_code}\n" -H "Authorization: token ${{ inputs.token }}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/orgs/${repo[0]}/repos" -d '{"name": "'"${repo[1]}"'"}')

        if [ $HTTPD_CODE === 200 ]; then
            mkdir -p tmp-readme
            if test -f "tmp-repo/README.md"; then
                cp tmp-repo/README.md tmp-readme/
            else
                echo "${{ inputs.source-repository }} ( BACKUP )" >> tmp-readme/README.md
            fi
            cd tmp-readme
            git init
            git config user.name "GitHub Actions Bot"
            git config user.email "<actions@github.com>"
            git remote add origin https://${{ inputs.token }}@github.com/${{ inputs.target-repository }}.git
            git branch -M main
            git fetch --all
            git add README.md
            git commit -am "Copy README.md"
            git push -u origin main
        fi
      shell: bash
    - run: |
        t=$( echo "${{ inputs.topics }}" | tr -d ' ')
        if [ ! -z "$t" ]; then
          curl -X PUT -H "Authorization: token ${{ inputs.token }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ inputs.target-repository }}/topics -d '{"names": ['"$(printf '"%s"\n' "${t//,/\",\"}")"']}'
        fi
      shell: bash
    - run: |
        cd tmp-repo/
        rm -rf .git
        git init
        git config user.name "GitHub Actions Bot"
        git config user.email "<actions@github.com>"
        git remote add origin https://${{ inputs.token }}@github.com/${{ inputs.target-repository }}.git
        git branch -M main
        git fetch --all
        REF="sha-${{ inputs.ref }}"
        $EXISTS=$(git branch --list $REF)
        if [[ -z "$EXISTS" ]]; then
            echo "Branch name sha-${{ inputs.ref }} already exists."
            exit 1
        fi
        git checkout -b sha-${{ inputs.ref }}
        git add -A
        git commit -am "SHA: ${{ inputs.ref }}"
        git push -u origin sha-${{ inputs.ref }}
        exit 0
      shell: bash
      env:
        REF: ${{ inputs.ref }}
