name: 'Backup repository'
description: >
    Create a repository backup

inputs:
  token:
    description: >
        Personal access token (PAT) used to fetch the repository. Default: empty. This field is optional, required if app credentials are not defined.
    required: true
  source-repository:
    description: >
        Source repository.
    required: true
  target-repository:
    description: >
        Target repository name.
    required: true
  topics:
    description: >
        Topics to add on destination repository
    default: 'backup'

runs:
  using: "composite"
  steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - run: |
        git clone --mirror https://${{ inputs.token }}@github.com/${{ inputs.source-repository }}.git tmp-repo
      shell: bash
    - run: |
        IFS='/'
        read -a repo <<< "${{ inputs.target-repository }}"
        curl -X POST -H "Authorization: token ${{ inputs.token }}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/orgs/${repo[0]}/repos" -d '{"name": "'"${repo[1]}"'"}'
      shell: bash
    - run: |
        t=$( echo "${{ inputs.topics }}" | tr -d ' ')
        if [ ! -z "$t" ]; then
          curl -X PUT -H "Authorization: token ${{ inputs.token }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ inputs.target-repository }}/topics -d '{"names": ['"$(printf '"%s"\n' "${t//,/\",\"}")"']}'
        fi
      shell: bash
    - run: |
        cd tmp-repo
        git config user.name "GitHub Actions Bot"
        git config user.email "<actions@github.com>"
        #git push --force --mirror https://${{ inputs.token }}@github.com/${{ inputs.target-repository }}.git
        git remote add origin https://${{ inputs.token }}@github.com/${{ inputs.target-repository }}.git
        git push origin --all  # push all branches
        git push origin --tags # push all tags
        git push origin refs/remotes/* #push the remote refs
      shell: bash
