name: 'Backup repository'
description: >
    Create a repository backup

inputs:
  token:
    description: >
        Personal access token (PAT) used to fetch the repository. Default: empty. This field is optional, required if app credentials are not defined.
    required: true
  source-repository:
    description: >
        Source repository.
    required: true
  owner:
    description: >
        Target repository owner
    required: true
  target-repository-name:
    description: >
        Target repository name.
    required: true
  topics:
    description: >
        Topics to add on destination repository
    default: "backup"

runs:
  using: "composite"
  steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        token: ${{ inputs.token }}
        repository: ${{ inputs.source-repository }}
        ref: main
        path: temp-repo
    - run: |
        curl -X POST -H "Authorization: token ${{ inputs.token }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/${{ inputs.owner }}/repos -d '{"name":"${{ inputs.target-repository-name }}"}'
      shell: bash
    - run: |
        curl -X PUT -H "Authorization: token ${{ inputs.token }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ inputs.owner }}/${{ inputs.target-repository-name }}/topics -d '{"names":["${{ inputs.topics }}"]}'
      shell: bash
    - run: |
        ls -la
      shell: bash
    - run: |
        cd temp-repo
        git init -b main
        git config user.name "GitHub Actions Bot" && git config user.email "<>"
        git add .
        git commit -m "First commit"
        git remote add origin ${{ inputs.target-repository-name }}
        git remote -v
        git push origin main
      shell: bash
