name: Repository backup

on:
  push:
    branches:
      - 'main'

jobs:
  backup-repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Backup repository
        uses: ./
        with:
          token: ${{ secrets.USER_PAT }}
          source-repository: the-iron-bank-of-braavos/test-octokit
          target-repository: the-iron-bank-of-braavos/test-octokit-backup
          topics: 'backup, test, sha'
          ref: 300080b7d0d231307a6c8c037ddbca3694b74cb2
