name: Repository backup test workflow

on:
  workflow_dispatch:
    inputs:
      token:
        type: text
        required: true
        description: "Token with write access in the target repository"
      source-repo:
        type: text
        required: true
        description: "The sourcecode repository identified by organization/repository to retrieve the commit from"
        default: "actions/checkout"
      ref:
        type: text
        required: true
        description: "The commit to retrieve from the source repository"
        default: "ec3a7ce113134d7a93b817d10a8272cb61118579"
      target-repo:
        type: text
        required: true
        description: "The target repository identified by organization/repository to store the sourcecode repository commit"

jobs:
  backup-repository:
    runs-on: ubuntu-latest
    steps:
    
      - name: Mask the input token
        run: |
          maskedtoken=$(cat $GITHUB_EVENT_PATH | jq '.inputs.token' | sed 's/"//g' )
          echo ::add-mask::$maskedtoken

      - name: Checkout this action
        uses: actions/checkout@v2

      - name: Backup repository
        uses: ./
        with:
          token: ${{ github.event.inputs.token }}
          source-repository: ${{ github.event.inputs.source-repo }}
          target-repository: ${{ github.event.inputs.target-repo }}
          topics: 'backup, test, sha'
          ref: ${{ github.event.inputs.ref }}
