name: Repository backup

on:
  push:
    branches:
      - 'test-if'

jobs:
  backup-repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Backup repository
        uses: ./
        with:
          token: ${{ secrets.USER_PAT }}
          source-repository: no-existe
          target-repository: the-iron-bank-of-braavos/test-octokit-backup2
          topics: 'backup, test, sha'
          ref: 56984d1854b126dc00edbf5b477c18f9d94a91cb
