name: Repository backup

on:
  push:
    branches:
      - 'test-if'

jobs:
  backup-repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Backup repository
        uses: ./
        with:
          token: ${{ secrets.USER_PAT }}
          source-repository: the-iron-bank-of-braavos/test-octokit
          target-repository: the-iron-bank-of-braavos/test-octokit-backup
          topics: 'backup, test, sha'
          ref: ff4b0a5d9ef36ee3c326f1894d87cbeac0bc3713
