name: Repository backup

on:
  push:
    branches:
      - 'test-if'

jobs:
  backup-repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Backup repository
        uses: ./
        with:
          token: ${{ secrets.USER_PAT }}
          source-repository: the-iron-bank-of-braavos/test-octokit
          target-repository: ivanamat/test-octokit-backup
          topics: 'backup, test, sha'
          ref: c345ac932fd2908ae43c866281d1e538e26693c9
